// <auto-generated />
using System;
using Auth.NET.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthSample.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.NET.Libs.Domain.Auditing.TAuditLog<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);

                    b.HasDiscriminator().HasValue("TAuditLog<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Roles.TRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator().HasValue("TRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Roles.TUserRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasDiscriminator().HasValue("TUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Tokens.TToken<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TokenValue")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Tokens", (string)null);

                    b.HasDiscriminator().HasValue("TToken<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Users.TUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFailedAttempt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CellPhone")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PasswordHash")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("TUser<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Auth.NET.Libs.Entities.Auditing.AuditLog", b =>
                {
                    b.HasBaseType("Auth.NET.Libs.Domain.Auditing.TAuditLog<string>");

                    b.HasDiscriminator().HasValue("AuditLog");
                });

            modelBuilder.Entity("Auth.NET.Libs.Entities.Roles.Role", b =>
                {
                    b.HasBaseType("Auth.NET.Libs.Domain.Roles.TRole<string>");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("Auth.NET.Libs.Entities.Roles.UserRole", b =>
                {
                    b.HasBaseType("Auth.NET.Libs.Domain.Roles.TUserRole<string>");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("Auth.NET.Libs.Entities.Tokens.Token", b =>
                {
                    b.HasBaseType("Auth.NET.Libs.Domain.Tokens.TToken<string>");

                    b.HasDiscriminator().HasValue("Token");
                });

            modelBuilder.Entity("Auth.NET.Libs.Entities.Users.User", b =>
                {
                    b.HasBaseType("Auth.NET.Libs.Domain.Users.TUser<string>");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Auditing.TAuditLog<string>", b =>
                {
                    b.HasOne("Auth.NET.Libs.Domain.Users.TUser<string>", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Roles.TUserRole<string>", b =>
                {
                    b.HasOne("Auth.NET.Libs.Domain.Roles.TRole<string>", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("Auth.NET.Libs.Domain.Users.TUser<string>", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Tokens.TToken<string>", b =>
                {
                    b.HasOne("Auth.NET.Libs.Domain.Users.TUser<string>", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Roles.TRole<string>", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Auth.NET.Libs.Domain.Users.TUser<string>", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
